"""
Version information for the app component
Generated by version-it
"""

__version__ = "1.0.42"
__scheme__ = "semantic"
__channel__ = ""
__git_commit__ = "ca3b003ad6c0aab5f9bf61f6c15729a52ad7c142"
__git_branch__ = "v2"
__build_date__ = "2025-10-10"