"""
Version information for the app component
Generated by version-it
"""

__version__ = "1.0.15"
__scheme__ = "semantic"
__channel__ = "stable"
__git_commit__ = "abc1234"
__git_branch__ = "main"
__build_date__ = "2025-10-10"