"""
Version information for the app component
Generated by version-it
"""

__version__ = "1.0.29"
__scheme__ = "semantic"
__channel__ = ""
__git_commit__ = "ce8477e"
__git_branch__ = "v2"
__build_date__ = "2025-10-10"