"""
Version information for the app component
Generated by version-it
"""

__version__ = "25.10.17"
__scheme__ = "semantic"
__channel__ = ""
__git_commit__ = "aa8fdb2"
__git_branch__ = "v2"
__build_date__ = "2025-10-10"