[workspace]
members = ["crates/version-it-cli"]
resolver = "2"

[workspace.package]
authors = ["Your Name"]
description = "A semantic versioning tool for CI pipelines"
edition = "2021"
license = "MIT"
repository = "https://github.com/yourusername/version-it"
version = "0.1.0"
