[package]
name = "version-it-composer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
semver = "1.0"
version-it-blocks = { path = "../version-it-blocks" }