name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build --release

    - name: Run CLI example
      run: cargo run --bin version-it -- bump --version 1.0.0 --bump patch