name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enter Nix shell
      run: nix develop --command "cargo test"

    - name: Build
      run: nix develop --command "cargo build --release"

    - name: Run CLI example
      run: nix develop --command "cargo run --bin version-it -- bump --version 1.0.0 --bump patch"